module.exports = [
  { first: 'SarahG', last: 'Geyer' },
  { first: 'SarahB', last: 'Bixler' },
  { first: 'Cara', last: 'Ottmar' },
  { first: 'Joanna', last: 'Coll' },
  { first: 'Dawn', last: 'Aldrich' },
  { first: 'Mario', last: 'Flores' },
  { first: 'Joshua', last: 'Frederickson' },
  { first: 'Josiah', last: 'Green' },
  { first: 'Ryan', last: 'Groesch' },
  { first: 'Kris', last: 'Sakarias' },
  { first: 'Lacy', last: 'Hogan' },
  { first: 'Panos', last: 'Kumasaka' },
  { first: 'Collin', last: 'Meredith' },
  { first: 'Michael', last: 'Castor' },
  { first: 'Sean', last: 'Miller' },
  { first: 'Daniel', last: 'Shelton' },
  { first: 'David', last: 'Stoll' },
  { first: 'Jennifer', last: 'Williams' },
  { first: 'Wyatt', last: 'Pefley' },
];
